const ACTION_TYPES = {
  API_PENDING: 'API_PENDING',
  API_SUCCESS: 'API_SUCCESS',
  API_ERROR: 'API_ERROR',
  GET_CHECK: 'GET_CHECK',
  GET_TRUE: 'GET_TRUE',
  GET_FALSE: 'GET_FALSE'

};
export default ACTION_TYPES;


