const ACTION_TYPES = {
  API_PENDING: 'API_PENDING',
  API_SUCCESS: 'API_SUCCESS',
  API_ERROR: 'API_ERROR',
  GET_CHECK: 'GET_CHECK',
  GET_USER: 'GET_USER',
  GET_TRUE: 'GET_TRUE',
  GET_FALSE: 'GET_FALSE',
  GET_ID:'GET_ID',
  GET_LAST_NAME:'GET_LAST_NAME',
  POST_PUBLIC:'POST_PUBLIC',
  PAYMENT_CHECKOUT: 'PAYMENT_CHECKOUT',
  SEARCH_KEYWORD:'SEARCH_KEYWORD',
  FETCH_ALL_POSTS:'FETCH_ALL_POSTS',
  GET_FILTERED:'GET_FILTERED',
  ADD_FILTER:'ADD_FILTER',
  CLEAN_FILTER:'CLEAN_FILTER',
  APPLY_FILTERS:'APPLY_FILTERS',
  DELETE_SINGLE_FILTER:'DELETE_SINGLE_FILTER',
};
export default ACTION_TYPES;


