const ACTION_TYPES = {
  API_PENDING: 'API_PENDING',
  API_SUCCESS: 'API_SUCCESS',
  API_ERROR: 'API_ERROR',
  GET_CHECK: 'GET_CHECK',
  GET_TRUE: 'GET_TRUE',
  GET_FALSE: 'GET_FALSE',
  GET_ID:'GET_ID',
  GET_LAST_NAME:'GET_LAST_NAME',
  POST_PUBLIC:'POST_PUBLIC',
  SEARCH_KEYWORD:'SEARCH_KEYWORD'
};
export default ACTION_TYPES;


